replicaCount: 2

image:
  repository: ghcr.io/francisegenti/taskforge
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: taskforge.example.com   # Change later to your domain or use LoadBalancer

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# For monitoring
serviceMonitor:
  enabled: true